/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.demo;

import java.awt.event.*;
import java.io.*;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.Charset;
import javax.swing.*;

/**
 *
 * @author root
 */
public class MyNoteUI extends javax.swing.JFrame {

	JFrame jFrame;
	JFileChooser fc;

	/**
	 * Creates new form MyNoteUI
	 */
	public MyNoteUI() {
		
		initComponents();

		jFrame = new javax.swing.JFrame();
		jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		jFrame.setContentPane(new PopupMenuExample());
		jFrame.setTitle("My NoteUI");

	}
	
	public String readFile(String path) throws IOException {
		System.out.println("The opened file path is: "+path);
		try (FileInputStream stream = new FileInputStream(new File(path))) {
			FileChannel filechannel;
			filechannel = stream.getChannel();
			MappedByteBuffer bb = filechannel.map(FileChannel.MapMode.READ_ONLY, 0, filechannel.size());
			/* Instead of using default, pass in a decoder. */
			return Charset.defaultCharset().decode(bb).toString();
		}
	}
	

	// This action creates and shows a modal open-file dialog.
	public class OpenFileAction extends AbstractAction {

		JFrame frame;
		JFileChooser chooser;

		OpenFileAction(JFrame frame, JFileChooser chooser) {
			super("Open...");
			this.chooser = chooser;
			this.frame = frame;
		}

		@Override
		public void actionPerformed(ActionEvent evt) {
			// Show dialog; this method does not return until dialog is closed
			chooser.showOpenDialog(frame);

			// Get the selected file
			
			File file = chooser.getSelectedFile();
			//jTextArea1.setText("The opended file path is: "+file.toString());

			try{
				jTextArea1.setText(readFile(file.toString()));
			} catch(Exception e)
			{
				System.err.println(e);	
			}
		}
	};

	public class SaveFileAction extends AbstractAction {

		JFileChooser chooser;
		JFrame frame;

		SaveFileAction(JFrame frame, JFileChooser chooser) {
			super("Save...");
			this.chooser = chooser;
			this.frame = frame;
		}

		@Override
		public void actionPerformed(ActionEvent evt) {

			// Get the selected file
			File file = fc.getSelectedFile();
			
			try {
				// Create file 
				System.out.println("The file path is: "+file.toString());
				FileWriter fstream = new FileWriter(file.toString());
				try (BufferedWriter out = new BufferedWriter(fstream)) {
					out.write(jTextArea1.getText());
				}
			} catch (Exception e) {//Catch exception if any
				System.err.println("Error: " + e.getMessage());
			}	
		}
	};

	// This action creates and shows a modal save-file dialog.
	public class SaveAsFileAction extends AbstractAction {

		JFileChooser chooser;
		JFrame frame;

		SaveAsFileAction(JFrame frame, JFileChooser chooser) {
			super("Save As...");
			this.chooser = chooser;
			this.frame = frame;
		}

		@Override
		public void actionPerformed(ActionEvent evt) {
			// Show dialog; this method does not return until dialog is closed
			chooser.showSaveDialog(frame);

			// Get the selected file
			File file = chooser.getSelectedFile();
			
			try {
				// Create file 
				System.out.println("The file path is: "+file.toString());
				FileWriter fstream = new FileWriter(file.toString());
				try (BufferedWriter out = new BufferedWriter(fstream)) {
					out.write(jTextArea1.getText());
				}
			} catch (Exception e) {//Catch exception if any
				System.err.println("Error: " + e.getMessage());
			}	
		}
	};

	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jButton1 = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButton1.setText("Open");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                jButton2.setText("Close");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setText("Save as");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jButton4.setText("Save");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton5.setText("Help");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(35, 35, 35)
                                                .addComponent(jButton4)
                                                .addGap(32, 32, 32)
                                                .addComponent(jButton3)
                                                .addGap(29, 29, 29)
                                                .addComponent(jButton2)
                                                .addGap(33, 33, 33)
                                                .addComponent(jButton5)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jButton1)
                                        .addComponent(jButton4)
                                        .addComponent(jButton3)
                                        .addComponent(jButton2)
                                        .addComponent(jButton5))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents


        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		System.exit(0);
        }//GEN-LAST:event_jButton2ActionPerformed
	
	// Open
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		jTextArea1.setText("");
		jTextArea1.append("Opening File...");

		// Create a file chooser
		String filename = File.separator + "home/tomxue";	// the default opened path
		fc = new JFileChooser(new File(filename));
		JFrame myframe = null;

		// Create the actions
		Action openAction = new OpenFileAction(myframe, fc);
		openAction.actionPerformed(evt);
		
        }//GEN-LAST:event_jButton1ActionPerformed

	// Save as
        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		//jTextArea1.setText("");
		//jTextArea1.append("Save as...");
	
		// Create a file chooser
		String filename = File.separator + "home/tomxue";	// the default opened path
		fc = new JFileChooser(new File(filename));
		JFrame myframe = null;

		// Create the actions
		Action saveAction = new SaveAsFileAction(myframe, fc);
		saveAction.actionPerformed(evt);
        }//GEN-LAST:event_jButton3ActionPerformed

	// Save
        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                /// Create a file chooser
		String filename = File.separator + "home/tomxue";	// the default opened path
		//fc = new JFileChooser(new File(filename));
		JFrame myframe = null;

		// Create the actions
		Action saveAction = new SaveFileAction(myframe, fc);
		saveAction.actionPerformed(evt);
        }//GEN-LAST:event_jButton4ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        }//GEN-LAST:event_jButton5ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MyNoteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MyNoteUI().setVisible(true);

			}
		});

	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        // End of variables declaration//GEN-END:variables
}